name: Resualbe  workflow
on:
    workflow_call:
          inputs:
            xxx: 
              description: 'A build passed from the caller workflow'
              default: build   
              required: false
              type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts 
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.xxx}}           
          path: build                 

      - name: Output contents          
        run: |
          ls -R 

      - name: Deploy
        run: echo "Deploying..."
